### ISSUE TITLE
BrickDimension.Orientation has wrong value when orientation `isFlat`

### ISSUE THREAD

**Issue by rubencagnie** [wayfair/brickkit-ios#13]
BrickDimension.Orientation doesn't work correctly when the device `isFlat`. Then it defaults to `landscape`. This should be fixed by checking the current frame's sizes

**Comment by klundberg** [comment]
`BrickDimensionDeviceInfo` in `BrickDimension.swift` seems to check the device's orientation for that, but we should check the screen's user interface orientation instead (which doesn't have a faceUp or faceDown option). That will remove the need to check any frame size (which may not be correct anyways, since a brick collection view might be shorter than it is wide if it's a child of another view controller with other UI in it.
